sudo: false
language: go
go:
  - 1.8.x
  - 1.9.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

script:
 - go test -race -v ./...
 - $HOME/gopath/bin/goveralls -service=travis-ci